version: '3.4'
services:
  app:
    # name image
    image: '${IMAGE}'
    # setup for build image (path for dockerfile e target in docker file [not mandatory])
    build:
      context: ./
      # Target use in dockerfile with multiple setup (example: local, prod)
      target: '${TARGET}'
    entrypoint: bash -c '${COMMAND}'
    ports:
      - 3777:4000
    # One of the main advantages of using Docker volumes
    # is the possibility of changing the content/configuration
    # of a container without the need to recreate it.
    volumes:
     - './:/app'